(function () {

    function byId(id) {

        return document.getElementById(id);
    }

    function getElements() {

        return {
            addContactsFileBtn:
                byId("addContactsFileBtn"),
            alignmentDropdownMenu:
                byId("alignmentDropdownMenu"),
            appVersionLabel:
                byId("appVersionLabel"),
            broadcastStatus:
                byId("broadcastStatus"),
            cleanAllLogsBtn:
                byId("cleanAllLogsBtn"),
            connectBtn:
                byId("connectBtn"),
            connectTelegramBtn:
                byId("connectTelegramBtn"),
            connectionPanel:
                byId("connectionsPanel"),
            connectionStatus:
                byId("connectionStatus"),
            connectionTile:
                byId("connectionTile"),
            connectionTimer:
                byId("connectionTimer"),
            contactFileName:
                byId("contactFileName"),
            emojiDropdownMenu:
                byId("emojiDropdownMenu"),
            contactEditorPage:
                byId("contactEditorPage"),
            contactsAddFileBtn:
                byId("contactsAddFileBtn"),
            contactsBackToSenderBtn:
                byId("contactsBackToSenderBtn"),
            contactsCount:
                byId("contactsCount"),
            contactsNavBtn:
                byId("contactsNavBtn"),
            contactsPage:
                byId("contactsPage"),
            contactsPanel:
                byId("contactsPanel"),
            contactsPreviewBtn:
                byId("contactsPreviewBtn"),
            failedCountEl:
                byId("failedCount"),
            headerTelegramBadge:
                byId("headerTelegramBadge"),
            headerTelegramStatus:
                byId("headerTelegramStatus"),
            headerWhatsAppBadge:
                byId("headerWhatsAppBadge"),
            headerWhatsAppStatus:
                byId("headerWhatsAppStatus"),
            helpNavBtn:
                byId("helpNavBtn"),
            linkApplyBtn:
                byId("linkApplyBtn"),
            linkCancelBtn:
                byId("linkCancelBtn"),
            linkDropdownMenu:
                byId("linkDropdownMenu"),
            linkUrlInput:
                byId("linkUrlInput"),
            logs:
                byId("logs"),
            logsNavBtn:
                byId("logsNavBtn"),
            logsPanel:
                byId("logsPanel"),
            mainPage:
                byId("mainPage"),
            mediaBtn:
                byId("mediaBtn"),
            mediaDropZone:
                byId("mediaDropZone"),
            mediaDropPrompt:
                byId("mediaDropPrompt"),
            mediaFileName:
                byId("mediaFileName"),
            mediaFileSize:
                byId("mediaFileSize"),
            mediaProgressBar:
                byId("mediaProgressBar"),
            mediaProgressLabel:
                byId("mediaProgressLabel"),
            mediaSelectedRow:
                byId("mediaSelectedRow"),
            mediaPanel:
                byId("mediaPanel"),
            mediaThumbnail:
                byId("mediaThumbnail"),
            mediaThumbnailBadge:
                byId("mediaThumbnailBadge"),
            mediaThumbnailIcon:
                byId("mediaThumbnailIcon"),
            mediaThumbnailImage:
                byId("mediaThumbnailImage"),
            mediaUploadCard:
                byId("mediaUploadCard"),
            mediaUploadHint:
                byId("mediaUploadHint"),
            mediaUploadTitle:
                byId("mediaUploadTitle"),
            removeMediaBtn:
                byId("removeMediaBtn"),
            mediaStatus:
                byId("mediaStatus"),
            openFailedLogsBtn:
                byId("openFailedLogsBtn"),
            openSuccessLogsBtn:
                byId("openSuccessLogsBtn"),
            pauseBtn:
                byId("pauseBtn"),
            previewBtn:
                byId("previewBtn"),
            previewContainer:
                byId("previewContainer"),
            progressBar:
                byId("progressBar"),
            progressText:
                byId("progressText"),
            providerSelect:
                byId("providerSelect"),
            qrImage:
                byId("qrImage"),
            resumeBtn:
                byId("resumeBtn"),
            retryFailedBtn:
                byId("retryFailedBtn"),
            saveTemplateBtn:
                byId("saveTemplateBtn"),
            senderNavBtn:
                byId("senderNavBtn"),
            skippedCountEl:
                byId("skippedCount"),
            startBtn:
                byId("startBtn"),
            status:
                byId("status"),
            statusBarConnection:
                byId("statusBarConnection"),
            statusBarContacts:
                byId("statusBarContacts"),
            statusBarReady:
                byId("statusBarReady"),
            statusBarTime:
                byId("statusBarTime"),
            stopBtn:
                byId("stopBtn"),
            successCountEl:
                byId("successCount"),
            settingsNavBtn:
                byId("settingsNavBtn"),
            telegramConnectionStatus:
                byId("telegramConnectionStatus"),
            telegramLoginLink:
                byId("telegramLoginLink"),
            telegramQrImage:
                byId("telegramQrImage"),
            telegramQrPanel:
                byId("telegramQrPanel"),
            templateCharCount:
                byId("templateCharCount"),
            templateInput:
                byId("templateInput"),
            templatePreview:
                byId("templatePreview"),
            templatePreviewToggle:
                byId("templatePreviewToggle"),
            templatesNavBtn:
                byId("templatesNavBtn"),
            templatesPanel:
                byId("templatesPanel"),
            toastContainer:
                byId("toastContainer"),
            validateBtn:
                byId("validateBtn"),
            validationPanel:
                byId("validationPanel"),
            validationSummary:
                byId("validationSummary"),
            variableDropdownMenu:
                byId("variableDropdownMenu"),
            validationWarnings:
                byId("validationWarnings")
        };
    }

    window.BroadcastRendererDom = {
        byId,
        getElements
    };
})();
